### ISSUE TITLE
Is this in conda?

### ISSUE THREAD

**Issue by tseemann** [rrwick/Core-SNP-filter#1]
If this is in bioconda can you inlcude this fact with instructions on installing it via bioconda?

If not, please can you get it into bioconda :)

Thanks!

**Comment by rrwick** [comment]
Yes, it is on bioconda: https://bioconda.github.io/recipes/core-snp-filter/README.html

I've recently updated the recipe to include ARM64 builds, and conda installation instructions are now in the README 🐍
