### ISSUE TITLE
Ungraceful error on /dev/null input

### ISSUE THREAD

**Issue by tseemann** [rrwick/Core-SNP-filter#3]
```
% coresnpfilter /dev/null

thread 'main' panicked at '"/dev/null" is too small', src/misc.rs:43:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```

```
% coresnpfilter /dev/zero
thread 'main' panicked at 'Error reading record: InvalidStart { line: 1, found: 0 }', src/misc.rs:68:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by rrwick** [comment]
Fixed in  ad3ce0d. It now explicitly checks for an empty input, so your example should look like this:
```
% coresnpfilter /dev/null

Error: /dev/null is empty
```

That commit also tidies up other error messages, displaying `Error:` instead of `thread 'main' panicked`.

Thanks!
