### ISSUE TITLE
Stats about how much was removed?

### ISSUE THREAD

**Issue by tseemann** [rrwick/Core-SNP-filter#4]
I notice some per site stats to stderr when using --verbose mode
Could you also print some overall stats?
kike %genome kept, %invariant, %variant?

**Comment by tseemann** [comment]
It seems you DO print stats, but NOT when --verbose is used?

**Comment by rrwick** [comment]
In f786b76, I made the stderr output a bit nicer, with some more data and using indentation to indicate which values sum to other values.

And in 025b475, I changed the `--verbose` option (which replaced the normal stderr with a table) to `--table`. So now the normal stderr is always displayed, whether or not a table is created. Should be simpler to use!
