### ISSUE TITLE
Invariant site stats for IQTREE

### ISSUE THREAD

**Issue by tseemann** [rrwick/Core-SNP-filter#5]
If you pass an MSA to IQTREE that has invsaiant sites excluded (via --exlcude_invariant) then the scale on the tree will be wrong because it hasn't accounted for all the invariants in the stats.

snp-sites -c can prfovide the command line options to give to IQTREE with the number of a,c,t,g that were removed.

Could you support this ?

**Comment by rrwick** [comment]
Done! c70d91a

`coresnpfilter -C` now exists and behaves the same as `snp-sites -C`.
